services:
  app:
    container_name: gstav-frontend
    image: "gustav87/gstav-frontend:${TAG}"
    restart: always

  backend:
    container_name: gstav-backend
    image: "gustav87/gstav-backend:${TAG}"
    restart: always
    environment:
      - flickr_api_key=xyz
      - mailgun_domain=xyz.mailgun.org
      - mailgun_api_key=xyz-key-abc
      - mailgun_from=xyz

  db:
    container_name: gstav-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"

networks:
  default:
    name: nginx-proxy-network

