services:
  react1-backend:
    container_name: react1-backend
    image: "gustav87/react1-backend:${TAG}"
    restart: always

  react1-db:
    container_name: react1-db
    image: mongo
    restart: always
    ports:
      - "27020:27017"

networks:
  default:
    name: nginx-proxy-network

